/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;


CREATE TABLE IF NOT EXISTS `Article` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `title` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL,
  `content` longtext COLLATE utf8mb4_unicode_ci,
  `lead` varchar(191) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `slug` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL,
  `createdAt` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` datetime(3) NOT NULL,
  `image` varchar(191) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `Article_slug_key` (`slug`)
) ENGINE=InnoDB AUTO_INCREMENT=13 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;


/*!40000 ALTER TABLE `Article` DISABLE KEYS */;
INSERT INTO `Article` (`id`, `title`, `content`, `lead`, `slug`, `createdAt`, `updatedAt`, `image`) VALUES
	(1, 'Cras vitae hendrerit', '## Lorem Ipsum Dolor Sit\n\nVivamus lacinia lacinia orci, vitae volutpat dolor sodales eget. Etiam at suscipit lacus. Sed pellentesque, urna et **maximus** iaculis, eros erat vehicula ipsum, a pretium lectus tellus sed mi. Nulla ornare nibh vel aliquet efficitur. Pellentesque commodo ex nec ante tincidunt bibendum. Fusce efficitur lacus ut nunc dapibus mattis. Sed facilisis turpis sit amet mauris auctor, vel tristique eros feugiat.\n\n> Sed id nisi sagittis, dapibus leo vitae, auctor eros. Sed gravida mattis egestas. Nam arcu neque, molestie vitae nunc vitae, euismod eleifend nunc. Maecenas eros ex, condimentum in velit at, cursus elementum ipsum.&#x20;\n\nMauris volutpat, nulla id porta rutrum, est mauris varius velit, nec mollis dui ante non eros:\n\n* Duis&#x20;\n* Commodo&#x20;\n* Pellentesque&#x20;\n* Purus\n* Sed facilisis', 'Maecenas eros ex, condimentum in velit at, cursus elementum ipsum.', 'dummy-article-1', '2023-10-12 20:03:53.519', '2023-10-12 20:03:53.519', '/api/images/articles/1/original.jpeg'),
	(2, 'Sed adipiscing lacinia', '## Lorem Ipsum Dolor Sit\n\nVivamus lacinia lacinia orci, vitae volutpat dolor sodales eget. Etiam at suscipit lacus. Sed pellentesque, urna et **maximus** iaculis, eros erat vehicula ipsum, a pretium lectus tellus sed mi. Nulla ornare nibh vel aliquet efficitur. Pellentesque commodo ex nec ante tincidunt bibendum. Fusce efficitur lacus ut nunc dapibus mattis. Sed facilisis turpis sit amet mauris auctor, vel tristique eros feugiat.\n\n> Sed id nisi sagittis, dapibus leo vitae, auctor eros. Sed gravida mattis egestas. Nam arcu neque, molestie vitae nunc vitae, euismod eleifend nunc. Maecenas eros ex, condimentum in velit at, cursus elementum ipsum.&#x20;\n\nMauris volutpat, nulla id porta rutrum, est mauris varius velit, nec mollis dui ante non eros:\n\n* Duis&#x20;\n* Commodo&#x20;\n* Pellentesque&#x20;\n* Purus\n* Sed facilisis', 'Maecenas eros ex, condimentum in velit at, cursus elementum ipsum.', 'dummy-article-2', '2023-10-12 20:03:53.519', '2023-10-12 20:03:53.519', '/api/images/articles/2/original.jpeg'),
	(3, 'Vestibulum commodo justo', '## Lorem Ipsum Dolor Sit\n\nVivamus lacinia lacinia orci, vitae volutpat dolor sodales eget. Etiam at suscipit lacus. Sed pellentesque, urna et **maximus** iaculis, eros erat vehicula ipsum, a pretium lectus tellus sed mi. Nulla ornare nibh vel aliquet efficitur. Pellentesque commodo ex nec ante tincidunt bibendum. Fusce efficitur lacus ut nunc dapibus mattis. Sed facilisis turpis sit amet mauris auctor, vel tristique eros feugiat.\n\n> Sed id nisi sagittis, dapibus leo vitae, auctor eros. Sed gravida mattis egestas. Nam arcu neque, molestie vitae nunc vitae, euismod eleifend nunc. Maecenas eros ex, condimentum in velit at, cursus elementum ipsum.&#x20;\n\nMauris volutpat, nulla id porta rutrum, est mauris varius velit, nec mollis dui ante non eros:\n\n* Duis&#x20;\n* Commodo&#x20;\n* Pellentesque&#x20;\n* Purus\n* Sed facilisis', 'Maecenas eros ex, condimentum in velit at, cursus elementum ipsum.', 'dummy-article-3', '2023-10-12 20:03:53.519', '2023-10-12 20:03:53.519', '/api/images/articles/3/original.jpeg'),
	(4, 'Aenean non purus', '## Lorem Ipsum Dolor Sit\n\nVivamus lacinia lacinia orci, vitae volutpat dolor sodales eget. Etiam at suscipit lacus. Sed pellentesque, urna et **maximus** iaculis, eros erat vehicula ipsum, a pretium lectus tellus sed mi. Nulla ornare nibh vel aliquet efficitur. Pellentesque commodo ex nec ante tincidunt bibendum. Fusce efficitur lacus ut nunc dapibus mattis. Sed facilisis turpis sit amet mauris auctor, vel tristique eros feugiat.\n\n> Sed id nisi sagittis, dapibus leo vitae, auctor eros. Sed gravida mattis egestas. Nam arcu neque, molestie vitae nunc vitae, euismod eleifend nunc. Maecenas eros ex, condimentum in velit at, cursus elementum ipsum.&#x20;\n\nMauris volutpat, nulla id porta rutrum, est mauris varius velit, nec mollis dui ante non eros:\n\n* Duis&#x20;\n* Commodo&#x20;\n* Pellentesque&#x20;\n* Purus\n* Sed facilisis', 'Maecenas eros ex, condimentum in velit at, cursus elementum ipsum.', 'dummy-article-4', '2023-10-12 20:03:53.519', '2023-10-12 20:03:53.519', '/api/images/articles/4/original.jpeg'),
	(5, 'Fusce in fermentum', '## Lorem Ipsum Dolor Sit\n\nVivamus lacinia lacinia orci, vitae volutpat dolor sodales eget. Etiam at suscipit lacus. Sed pellentesque, urna et **maximus** iaculis, eros erat vehicula ipsum, a pretium lectus tellus sed mi. Nulla ornare nibh vel aliquet efficitur. Pellentesque commodo ex nec ante tincidunt bibendum. Fusce efficitur lacus ut nunc dapibus mattis. Sed facilisis turpis sit amet mauris auctor, vel tristique eros feugiat.\n\n> Sed id nisi sagittis, dapibus leo vitae, auctor eros. Sed gravida mattis egestas. Nam arcu neque, molestie vitae nunc vitae, euismod eleifend nunc. Maecenas eros ex, condimentum in velit at, cursus elementum ipsum.&#x20;\n\nMauris volutpat, nulla id porta rutrum, est mauris varius velit, nec mollis dui ante non eros:\n\n* Duis&#x20;\n* Commodo&#x20;\n* Pellentesque&#x20;\n* Purus\n* Sed facilisis', 'Maecenas eros ex, condimentum in velit at, cursus elementum ipsum.', 'dummy-article-5', '2023-10-12 20:03:53.519', '2023-10-12 20:03:53.519', '/api/images/articles/5/original.jpeg'),
	(6, 'Pellentesque aliquet mi', '## Lorem Ipsum Dolor Sit\n\nVivamus lacinia lacinia orci, vitae volutpat dolor sodales eget. Etiam at suscipit lacus. Sed pellentesque, urna et **maximus** iaculis, eros erat vehicula ipsum, a pretium lectus tellus sed mi. Nulla ornare nibh vel aliquet efficitur. Pellentesque commodo ex nec ante tincidunt bibendum. Fusce efficitur lacus ut nunc dapibus mattis. Sed facilisis turpis sit amet mauris auctor, vel tristique eros feugiat.\n\n> Sed id nisi sagittis, dapibus leo vitae, auctor eros. Sed gravida mattis egestas. Nam arcu neque, molestie vitae nunc vitae, euismod eleifend nunc. Maecenas eros ex, condimentum in velit at, cursus elementum ipsum.&#x20;\n\nMauris volutpat, nulla id porta rutrum, est mauris varius velit, nec mollis dui ante non eros:\n\n* Duis&#x20;\n* Commodo&#x20;\n* Pellentesque&#x20;\n* Purus\n* Sed facilisis', 'Maecenas eros ex, condimentum in velit at, cursus elementum ipsum.', 'dummy-article-6', '2023-10-12 20:03:53.519', '2023-10-12 20:03:53.519', '/api/images/articles/6/original.jpeg'),
	(7, 'Cras vel tristique', '## Lorem Ipsum Dolor Sit\n\nVivamus lacinia lacinia orci, vitae volutpat dolor sodales eget. Etiam at suscipit lacus. Sed pellentesque, urna et **maximus** iaculis, eros erat vehicula ipsum, a pretium lectus tellus sed mi. Nulla ornare nibh vel aliquet efficitur. Pellentesque commodo ex nec ante tincidunt bibendum. Fusce efficitur lacus ut nunc dapibus mattis. Sed facilisis turpis sit amet mauris auctor, vel tristique eros feugiat.\n\n> Sed id nisi sagittis, dapibus leo vitae, auctor eros. Sed gravida mattis egestas. Nam arcu neque, molestie vitae nunc vitae, euismod eleifend nunc. Maecenas eros ex, condimentum in velit at, cursus elementum ipsum.&#x20;\n\nMauris volutpat, nulla id porta rutrum, est mauris varius velit, nec mollis dui ante non eros:\n\n* Duis&#x20;\n* Commodo&#x20;\n* Pellentesque&#x20;\n* Purus\n* Sed facilisis', 'Maecenas eros ex, condimentum in velit at, cursus elementum ipsum.', 'dummy-article-7', '2023-10-12 20:03:53.519', '2023-10-12 20:03:53.519', '/api/images/articles/7/original.jpeg'),
	(8, 'In hac habitasse', '## Lorem Ipsum Dolor Sit\n\nVivamus lacinia lacinia orci, vitae volutpat dolor sodales eget. Etiam at suscipit lacus. Sed pellentesque, urna et **maximus** iaculis, eros erat vehicula ipsum, a pretium lectus tellus sed mi. Nulla ornare nibh vel aliquet efficitur. Pellentesque commodo ex nec ante tincidunt bibendum. Fusce efficitur lacus ut nunc dapibus mattis. Sed facilisis turpis sit amet mauris auctor, vel tristique eros feugiat.\n\n> Sed id nisi sagittis, dapibus leo vitae, auctor eros. Sed gravida mattis egestas. Nam arcu neque, molestie vitae nunc vitae, euismod eleifend nunc. Maecenas eros ex, condimentum in velit at, cursus elementum ipsum.&#x20;\n\nMauris volutpat, nulla id porta rutrum, est mauris varius velit, nec mollis dui ante non eros:\n\n* Duis&#x20;\n* Commodo&#x20;\n* Pellentesque&#x20;\n* Purus\n* Sed facilisis', 'Maecenas eros ex, condimentum in velit at, cursus elementum ipsum.', 'dummy-article-8', '2023-10-12 20:03:53.519', '2023-10-12 20:03:53.519', '/api/images/articles/8/original.jpeg'),
	(9, 'Ut facilisis ligula', '## Lorem Ipsum Dolor Sit\n\nVivamus lacinia lacinia orci, vitae volutpat dolor sodales eget. Etiam at suscipit lacus. Sed pellentesque, urna et **maximus** iaculis, eros erat vehicula ipsum, a pretium lectus tellus sed mi. Nulla ornare nibh vel aliquet efficitur. Pellentesque commodo ex nec ante tincidunt bibendum. Fusce efficitur lacus ut nunc dapibus mattis. Sed facilisis turpis sit amet mauris auctor, vel tristique eros feugiat.\n\n> Sed id nisi sagittis, dapibus leo vitae, auctor eros. Sed gravida mattis egestas. Nam arcu neque, molestie vitae nunc vitae, euismod eleifend nunc. Maecenas eros ex, condimentum in velit at, cursus elementum ipsum.&#x20;\n\nMauris volutpat, nulla id porta rutrum, est mauris varius velit, nec mollis dui ante non eros:\n\n* Duis&#x20;\n* Commodo&#x20;\n* Pellentesque&#x20;\n* Purus\n* Sed facilisis', 'Maecenas eros ex, condimentum in velit at, cursus elementum ipsum.', 'dummy-article-9', '2023-10-12 20:03:53.519', '2023-10-12 20:03:53.519', '/api/images/articles/9/original.jpeg'),
	(10, 'Proin eu bibendum', '## Lorem Ipsum Dolor Sit\n\nVivamus lacinia lacinia orci, vitae volutpat dolor sodales eget. Etiam at suscipit lacus. Sed pellentesque, urna et **maximus** iaculis, eros erat vehicula ipsum, a pretium lectus tellus sed mi. Nulla ornare nibh vel aliquet efficitur. Pellentesque commodo ex nec ante tincidunt bibendum. Fusce efficitur lacus ut nunc dapibus mattis. Sed facilisis turpis sit amet mauris auctor, vel tristique eros feugiat.\n\n> Sed id nisi sagittis, dapibus leo vitae, auctor eros. Sed gravida mattis egestas. Nam arcu neque, molestie vitae nunc vitae, euismod eleifend nunc. Maecenas eros ex, condimentum in velit at, cursus elementum ipsum.&#x20;\n\nMauris volutpat, nulla id porta rutrum, est mauris varius velit, nec mollis dui ante non eros:\n\n* Duis&#x20;\n* Commodo&#x20;\n* Pellentesque&#x20;\n* Purus\n* Sed facilisis', 'Maecenas eros ex, condimentum in velit at, cursus elementum ipsum.', 'dummy-article-10', '2023-10-12 20:03:53.519', '2023-10-12 20:03:53.519', '/api/images/articles/10/original.jpeg'),
	(11, 'Aliquam tincidunt posuere', '## Lorem Ipsum Dolor Sit\n\nVivamus lacinia lacinia orci, vitae volutpat dolor sodales eget. Etiam at suscipit lacus. Sed pellentesque, urna et **maximus** iaculis, eros erat vehicula ipsum, a pretium lectus tellus sed mi. Nulla ornare nibh vel aliquet efficitur. Pellentesque commodo ex nec ante tincidunt bibendum. Fusce efficitur lacus ut nunc dapibus mattis. Sed facilisis turpis sit amet mauris auctor, vel tristique eros feugiat.\n\n> Sed id nisi sagittis, dapibus leo vitae, auctor eros. Sed gravida mattis egestas. Nam arcu neque, molestie vitae nunc vitae, euismod eleifend nunc. Maecenas eros ex, condimentum in velit at, cursus elementum ipsum.&#x20;\n\nMauris volutpat, nulla id porta rutrum, est mauris varius velit, nec mollis dui ante non eros:\n\n* Duis&#x20;\n* Commodo&#x20;\n* Pellentesque&#x20;\n* Purus\n* Sed facilisis', 'Maecenas eros ex, condimentum in velit at, cursus elementum ipsum.', 'dummy-article-11', '2023-10-12 20:03:53.519', '2023-10-12 20:03:53.519', '/api/images/articles/11/original.jpeg'),
	(12, 'Vestibulum dignissim fringilla', '## Lorem Ipsum Dolor Sit\n\nVivamus lacinia lacinia orci, vitae volutpat dolor sodales eget. Etiam at suscipit lacus. Sed pellentesque, urna et **maximus** iaculis, eros erat vehicula ipsum, a pretium lectus tellus sed mi. Nulla ornare nibh vel aliquet efficitur. Pellentesque commodo ex nec ante tincidunt bibendum. Fusce efficitur lacus ut nunc dapibus mattis. Sed facilisis turpis sit amet mauris auctor, vel tristique eros feugiat.\n\n> Sed id nisi sagittis, dapibus leo vitae, auctor eros. Sed gravida mattis egestas. Nam arcu neque, molestie vitae nunc vitae, euismod eleifend nunc. Maecenas eros ex, condimentum in velit at, cursus elementum ipsum.&#x20;\n\nMauris volutpat, nulla id porta rutrum, est mauris varius velit, nec mollis dui ante non eros:\n\n* Duis&#x20;\n* Commodo&#x20;\n* Pellentesque&#x20;\n* Purus\n* Sed facilisis', 'Maecenas eros ex, condimentum in velit at, cursus elementum ipsum.', 'dummy-article-12', '2023-10-12 20:03:53.519', '2023-10-12 20:03:53.519', '/api/images/articles/12/original.jpeg');
/*!40000 ALTER TABLE `Article` ENABLE KEYS */;


CREATE TABLE IF NOT EXISTS `User` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL,
  `email` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL,
  `password` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL,
  `firstLogin` tinyint(1) NOT NULL DEFAULT '1',
  PRIMARY KEY (`id`),
  UNIQUE KEY `User_email_key` (`email`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;


/*!40000 ALTER TABLE `User` DISABLE KEYS */;
INSERT INTO `User` (`id`, `name`, `email`, `password`, `firstLogin`) VALUES
	(1, 'Test User', 'test@test.hu', '$2a$10$0ieu3TUi9M9AGHzjBYrnR.1uBWPEEjYTGm8ANwz97HMDu8w/a4/KK', 0);
/*!40000 ALTER TABLE `User` ENABLE KEYS */;

/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IFNULL(@OLD_FOREIGN_KEY_CHECKS, 1) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40111 SET SQL_NOTES=IFNULL(@OLD_SQL_NOTES, 1) */;
